function [posterior,estimate]=fit_model(fitted_type,ref_type,...
 dbname,...
 lin_prior_range,...
nonlin_prior_range,...
 training_trials_range,...
num_points_posterior_lin,...
num_points_posterior_nonlin,...
num_particles_lhd)
shuffle_db=false;
     if strcmp(fitted_type,'lin')
         [posterior,estimate]=fit_linear_model(ref_type, dbname,...
             lin_prior_range,training_trials_range,...
             num_points_posterior_lin,shuffle_db);
     elseif strcmp(fitted_type,'nonlin')
         [posterior, estimate]=fit_nonlinear_model(ref_type, dbname,...
             nonlin_prior_range,training_trials_range,...
            num_points_posterior_nonlin,num_particles_lhd,shuffle_db);
     end
end

