% plot MSE for nonlin-to-nonlin model fitting - using data from srvr
clear
lw=3;
noise=1.5;
trial_nb = 50:50:300;
M=length(trial_nb);
filenames = {'data/nonlinlin_mses500runs50trials.mat',...
    'data/nonlinlin_mses500runs100trials.mat',...
    'data/nonlinlin_mses500runs150trials.mat',...
    'data/nonlinlin_mses400runs200trials.mat',...
    'data/nonlinlin_mses400runs250trials.mat',...
    'data/nonlinlin_mses400runs300trials.mat'};
mse_vec = zeros(1,M);
for i = 1:M
    load(filenames{i})
    mse_vec(i)=mses;
end
plot(trial_nb, mse_vec,...
    'LineWidth',lw,... 
    'LineStyle','-.')
xlabel('trial nb')
ylabel('MSE')
title(['nonlinlin noise=',num2str(noise)])